### ISSUE TITLE
如果我想默认拒绝应该如何修改

### ISSUE THREAD

**Issue by FeranyDev** [zerorooot/HideMiuiClipboardDialog#1]
我想默认拒绝权限，但是我这样修改不生效。
![image](https://user-images.githubusercontent.com/43532576/203697150-a91f667f-1ee1-4cde-83d0-0483c0944a5e.png)

**Comment by zerorooot** [comment]
方法一：没记错的话recordCountEvent"只是记录，核心方法是

 XposedHelpers.callMethod(param.thisObject, "gotChoice", 3, true, true)

你hook相关方法输出看看

方法二：https://github.com/Thiasap/ClipboardFilter

方法三：在手机设置里搜"剪切板隐私保护"，点击全部拒绝
![Screenshot_2022-11-24-18-36-06-290_com miui securitycenter](https://user-images.githubusercontent.com/21277567/203763216-ff210ce3-c101-4dd1-80c8-3169af06074e.jpg)

**Comment by FeranyDev** [comment]
我把它改成这样
XposedHelpers.callMethod(param.thisObject, "gotChoice", 1, true, true) 
好像就可以了
